function y = basnPass(x,tx,f1,f2)
%  Preprocess input x
%    This function expects an input vector x and a vector of time values
%    tx. tx is a numeric vector in units of seconds.
%    Follow the timetable documentation (type 'doc timetable' in
%    command line) to learn how to index into a table variable and its time
%    values so that you can pass them into this function.

% Generated by MATLAB(R) 9.5 and Signal Processing Toolbox 8.1.
% Generated on: 30-Apr-2019 13:11:45
% x = normaliz(x);
Fs = 1/mean(diff(tx)); % Average sample rate
y = bandpass(x,[f1,f2],Fs,'Steepness',0.85,'StopbandAttenuation',60);
y = normalize(y);
end

